language:
  - cpp

before_install:
  - pip install --user cpp-coveralls
  
addons:
  sonarcloud:
    organization: "zdoroven-github"
    token:
      secure: $SONAR_TOKEN
      
script:
  - qmake
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  - sonar-scanner
  
cache:
  directories:
    - '$HOME/.sonar/cache'
  
notifications:
  email: false
